### ISSUE TITLE
TODO post install 2017

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/nosdeputes.fr#33]
- [x] freeze crons 2012
- [x] prepare conf 2017 NDD
- [x] update conf 2012 (freeze comments etc)
- [x] run first load MPs (cf script below)
- [x] import users from 2012
- [x] add doc Bureau
- [x] setup analytics/piwik
- [x] <s>add pics from wikipedia or professions de fois for missing ones ?</s> all pics already present on AN
- [x] add to MP data from old legislature (websites, twitter, collabs?, adresses, mails etc)
- [x] flip pictures
- [x] change in 2012 conf announce/host_next
- [x] setup url nouveau cpc to MPs réélus in 2012
- [x] import alertes from 2012 (only those on MPs reelected and keywors, not on comments and otther MPs)

TO run for first load: 
```
php symfony cc
php symfony doctrine:build --all --no-confirmation
php symfony index:Solr --removeAll=yes
bash bin/load_deputes
bash bin/load_url_ancien_cpc.sh
php symfony top:Deputes
php symfony set:Vacances
php symfony set:Session
php symfony index:Solr --pages=yes
php symfony index:Solr --all=yes
```
